#!/bin/bash

declare -A backlistArray

echo "Starting..."

ROOTDIR="/var/www/html/Database/Backup/Backups"
YEAR=`date +%Y`
MONTH=`date +%m`
DAY=`date +%d`
HOUR=`date +%H`
SERVER="mysql.local"

backlistArray=( ['information_schema']=1 ['performance_schema']=1 ['mysql']=1 ['sys']=1)

sshpass -p 'password' ssh user@ip '[ -d $ROOTDIR/$DAY-$MONTH-$YEAR ]'
if [[ $? -eq 0 ]]
then
    echo 'Directory exists'
else
    sshpass -p 'password' ssh user@ip  "mkdir -p $ROOTDIR/$DAY-$MONTH-$YEAR"
fi

echo "running dump"

dblist=`mysql -uroot -ppassword -e "show databases" | sed -n '2,$ p'`
for db in $dblist;
do
    echo "Backing up $db"

    if [[ ${backlistArray[$db]} ]]; then
       echo  "Database $db is on blacklist, skip"
    else
       mysqldump -uroot -ppassword --single-transaction --routines --triggers $db | gzip --best |sshpass -p 'password' ssh user@ip "cat > $ROOTDIR/$DAY-$MONTH-$YEAR/$db.sql.gz"
    fi
done

echo "dump completed in folder $ROOTDIR/$DAY-$MONTH-$YEAR"
